/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistema.views;

import java.net.URL;
import javax.swing.ImageIcon;
import java.awt.Color;
import javax.swing.JPanel;
import Controllers.Sistema;
import Sistema.models.Empleado;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Isabella
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private Sistema sistema;
    private ArrayList<IniciarSesion> iniciar;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     * @param sistema
     */
    public MenuPrincipal(Sistema sistema) {
        initComponents();
        this.sistema = sistema;
        this.setLocationRelativeTo(null);
        try {
        this.setIconImage(new ImageIcon(getClass().getResource("/Sistema/images/icons8-recursos-humanos-50.png")).getImage());
        } catch (Exception e) {
            System.out.println("Imagen no encontrada");
        }
        configurarMenuSegunRol();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAsignarEmpleado = new javax.swing.JPanel();
        lblIconAgregarEmpleado = new javax.swing.JLabel();
        lblNombreAgregar = new javax.swing.JLabel();
        btnBuscarEmpleado = new javax.swing.JPanel();
        lblIconBuscarEmpleado = new javax.swing.JLabel();
        lblNombreBuscar = new javax.swing.JLabel();
        btnMostrarEmpleado = new javax.swing.JPanel();
        lblIconMostrarEmpleado = new javax.swing.JLabel();
        lblNombreMostrar = new javax.swing.JLabel();
        btnActualizarEmpleado = new javax.swing.JPanel();
        lblIconActualizarEmpleado = new javax.swing.JLabel();
        lblNombreActualizar = new javax.swing.JLabel();
        btnEliminarEmpleado = new javax.swing.JPanel();
        lblIconEliminarEmpleado = new javax.swing.JLabel();
        lblNombreEliminar = new javax.swing.JLabel();
        btnGenerarReportEmp = new javax.swing.JPanel();
        lblIconGenerarReportEmp = new javax.swing.JLabel();
        lblNombreGenerarReportEmp = new javax.swing.JLabel();
        btnGenerarReportDep = new javax.swing.JPanel();
        lblIconGenerarReportDep = new javax.swing.JLabel();
        lblNombreGenerarReportDep = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setForeground(new java.awt.Color(102, 0, 204));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("Sistema RRHH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jPanel2.setBackground(new java.awt.Color(244, 232, 252));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAsignarEmpleado.setBackground(new java.awt.Color(244, 232, 252));
        btnAsignarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAsignarEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAsignarEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAsignarEmpleadoMouseExited(evt);
            }
        });

        lblIconAgregarEmpleado.setBackground(new java.awt.Color(204, 204, 255));
        lblIconAgregarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/images/icons8-agregar-administrador-80.png"))); // NOI18N
        lblIconAgregarEmpleado.setText("jLabel2");
        lblIconAgregarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIconAgregarEmpleadoMouseEntered(evt);
            }
        });

        lblNombreAgregar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblNombreAgregar.setText("Agregar empleado");

        javax.swing.GroupLayout btnAsignarEmpleadoLayout = new javax.swing.GroupLayout(btnAsignarEmpleado);
        btnAsignarEmpleado.setLayout(btnAsignarEmpleadoLayout);
        btnAsignarEmpleadoLayout.setHorizontalGroup(
            btnAsignarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNombreAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
            .addGroup(btnAsignarEmpleadoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblIconAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAsignarEmpleadoLayout.setVerticalGroup(
            btnAsignarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAsignarEmpleadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconAgregarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreAgregar))
        );

        jPanel2.add(btnAsignarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        btnBuscarEmpleado.setBackground(new java.awt.Color(244, 232, 252));
        btnBuscarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarEmpleadoMouseExited(evt);
            }
        });

        lblIconBuscarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/images/icons8-buscar-80.png"))); // NOI18N
        lblIconBuscarEmpleado.setText("jLabel3");

        lblNombreBuscar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblNombreBuscar.setText("Buscar empleado");

        javax.swing.GroupLayout btnBuscarEmpleadoLayout = new javax.swing.GroupLayout(btnBuscarEmpleado);
        btnBuscarEmpleado.setLayout(btnBuscarEmpleadoLayout);
        btnBuscarEmpleadoLayout.setHorizontalGroup(
            btnBuscarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarEmpleadoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblIconBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(btnBuscarEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
        );
        btnBuscarEmpleadoLayout.setVerticalGroup(
            btnBuscarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconBuscarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNombreBuscar))
        );

        jPanel2.add(btnBuscarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        btnMostrarEmpleado.setBackground(new java.awt.Color(244, 232, 252));
        btnMostrarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarEmpleadoMouseExited(evt);
            }
        });

        lblIconMostrarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/images/icons8-ver-80.png"))); // NOI18N
        lblIconMostrarEmpleado.setText("jLabel4");

        lblNombreMostrar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblNombreMostrar.setText("Mostrar empleado(s)");

        javax.swing.GroupLayout btnMostrarEmpleadoLayout = new javax.swing.GroupLayout(btnMostrarEmpleado);
        btnMostrarEmpleado.setLayout(btnMostrarEmpleadoLayout);
        btnMostrarEmpleadoLayout.setHorizontalGroup(
            btnMostrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNombreMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
            .addGroup(btnMostrarEmpleadoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblIconMostrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnMostrarEmpleadoLayout.setVerticalGroup(
            btnMostrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMostrarEmpleadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconMostrarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreMostrar))
        );

        jPanel2.add(btnMostrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        btnActualizarEmpleado.setBackground(new java.awt.Color(244, 232, 252));
        btnActualizarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarEmpleadoMouseExited(evt);
            }
        });

        lblIconActualizarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/images/icons8-actualizar-80.png"))); // NOI18N
        lblIconActualizarEmpleado.setText("jLabel5");

        lblNombreActualizar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblNombreActualizar.setText("Actualizar empleado");

        javax.swing.GroupLayout btnActualizarEmpleadoLayout = new javax.swing.GroupLayout(btnActualizarEmpleado);
        btnActualizarEmpleado.setLayout(btnActualizarEmpleadoLayout);
        btnActualizarEmpleadoLayout.setHorizontalGroup(
            btnActualizarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNombreActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
            .addGroup(btnActualizarEmpleadoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblIconActualizarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnActualizarEmpleadoLayout.setVerticalGroup(
            btnActualizarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnActualizarEmpleadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconActualizarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreActualizar))
        );

        jPanel2.add(btnActualizarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        btnEliminarEmpleado.setBackground(new java.awt.Color(244, 232, 252));
        btnEliminarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarEmpleadoMouseExited(evt);
            }
        });

        lblIconEliminarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/images/icons8-eliminar-80.png"))); // NOI18N
        lblIconEliminarEmpleado.setText("jLabel6");

        lblNombreEliminar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblNombreEliminar.setText("Eliminar empleado");

        javax.swing.GroupLayout btnEliminarEmpleadoLayout = new javax.swing.GroupLayout(btnEliminarEmpleado);
        btnEliminarEmpleado.setLayout(btnEliminarEmpleadoLayout);
        btnEliminarEmpleadoLayout.setHorizontalGroup(
            btnEliminarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNombreEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
            .addGroup(btnEliminarEmpleadoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblIconEliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnEliminarEmpleadoLayout.setVerticalGroup(
            btnEliminarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconEliminarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNombreEliminar))
        );

        jPanel2.add(btnEliminarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, -1, -1));

        btnGenerarReportEmp.setBackground(new java.awt.Color(244, 232, 252));
        btnGenerarReportEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarReportEmpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenerarReportEmpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenerarReportEmpMouseExited(evt);
            }
        });

        lblIconGenerarReportEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/images/icons8-crear-archivoEmp-80.png"))); // NOI18N

        lblNombreGenerarReportEmp.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblNombreGenerarReportEmp.setText("Generar reporte empleado");

        javax.swing.GroupLayout btnGenerarReportEmpLayout = new javax.swing.GroupLayout(btnGenerarReportEmp);
        btnGenerarReportEmp.setLayout(btnGenerarReportEmpLayout);
        btnGenerarReportEmpLayout.setHorizontalGroup(
            btnGenerarReportEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNombreGenerarReportEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnGenerarReportEmpLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblIconGenerarReportEmp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnGenerarReportEmpLayout.setVerticalGroup(
            btnGenerarReportEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGenerarReportEmpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconGenerarReportEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreGenerarReportEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(btnGenerarReportEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 41, -1, -1));

        btnGenerarReportDep.setBackground(new java.awt.Color(244, 232, 252));
        btnGenerarReportDep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarReportDepMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGenerarReportDepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGenerarReportDepMouseExited(evt);
            }
        });

        lblIconGenerarReportDep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sistema/images/icons8-crear-archivo-80.png"))); // NOI18N

        lblNombreGenerarReportDep.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        lblNombreGenerarReportDep.setText("Generar reporte departamento");

        javax.swing.GroupLayout btnGenerarReportDepLayout = new javax.swing.GroupLayout(btnGenerarReportDep);
        btnGenerarReportDep.setLayout(btnGenerarReportDepLayout);
        btnGenerarReportDepLayout.setHorizontalGroup(
            btnGenerarReportDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNombreGenerarReportDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGenerarReportDepLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconGenerarReportDep)
                .addGap(49, 49, 49))
        );
        btnGenerarReportDepLayout.setVerticalGroup(
            btnGenerarReportDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGenerarReportDepLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconGenerarReportDep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreGenerarReportDep, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(btnGenerarReportDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 41, -1, -1));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(244, 232, 252));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 820, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void entrandoMouse (JPanel panel){
        panel.setBackground(new Color(204,153,255));
    }
    
    private void saliendoMouse (JPanel panel){
        panel.setBackground(new Color(244,232,252));
    }
    
    private void lblIconAgregarEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconAgregarEmpleadoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconAgregarEmpleadoMouseEntered

    private void btnAsignarEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarEmpleadoMouseEntered
        this.entrandoMouse(btnAsignarEmpleado);
    }//GEN-LAST:event_btnAsignarEmpleadoMouseEntered

    private void btnBuscarEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoMouseEntered
        this.entrandoMouse(btnBuscarEmpleado);
    }//GEN-LAST:event_btnBuscarEmpleadoMouseEntered

    private void btnMostrarEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarEmpleadoMouseEntered
        this.entrandoMouse(btnMostrarEmpleado);
    }//GEN-LAST:event_btnMostrarEmpleadoMouseEntered

    private void btnActualizarEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarEmpleadoMouseEntered
        this.entrandoMouse(btnActualizarEmpleado);
    }//GEN-LAST:event_btnActualizarEmpleadoMouseEntered

    private void btnEliminarEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoMouseEntered
        this.entrandoMouse(btnEliminarEmpleado);
    }//GEN-LAST:event_btnEliminarEmpleadoMouseEntered

    private void btnGenerarReportEmpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReportEmpMouseEntered
        this.entrandoMouse(btnGenerarReportEmp);
    }//GEN-LAST:event_btnGenerarReportEmpMouseEntered

    private void btnGenerarReportDepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReportDepMouseEntered
        this.entrandoMouse(btnGenerarReportDep);
    }//GEN-LAST:event_btnGenerarReportDepMouseEntered

    private void btnAsignarEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarEmpleadoMouseExited
        this.saliendoMouse(btnAsignarEmpleado);
    }//GEN-LAST:event_btnAsignarEmpleadoMouseExited

    private void btnBuscarEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoMouseExited
        this.saliendoMouse(btnBuscarEmpleado);
    }//GEN-LAST:event_btnBuscarEmpleadoMouseExited

    private void btnMostrarEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarEmpleadoMouseExited
        this.saliendoMouse(btnMostrarEmpleado);
    }//GEN-LAST:event_btnMostrarEmpleadoMouseExited

    private void btnActualizarEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarEmpleadoMouseExited
        this.saliendoMouse(btnActualizarEmpleado);
    }//GEN-LAST:event_btnActualizarEmpleadoMouseExited

    private void btnEliminarEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoMouseExited
        this.saliendoMouse(btnEliminarEmpleado);
    }//GEN-LAST:event_btnEliminarEmpleadoMouseExited

    private void btnGenerarReportEmpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReportEmpMouseExited
        this.saliendoMouse(btnGenerarReportEmp);
    }//GEN-LAST:event_btnGenerarReportEmpMouseExited

    private void btnGenerarReportDepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReportDepMouseExited
        this.saliendoMouse(btnGenerarReportDep);
    }//GEN-LAST:event_btnGenerarReportDepMouseExited

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
        
        IniciarSesion iniciar= new IniciarSesion(null, true, sistema);
        iniciar.setVisible(true);
        
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMostrarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarEmpleadoMouseClicked
        MostrarEmpleado ventana = new MostrarEmpleado(this,true,sistema);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnMostrarEmpleadoMouseClicked

    private void btnAsignarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarEmpleadoMouseClicked
        AsignarEmpleado ventana = new AsignarEmpleado(this,true,sistema);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnAsignarEmpleadoMouseClicked

    private void btnBuscarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoMouseClicked
        BuscarEmpleado ventana = new BuscarEmpleado(this, true, sistema);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnBuscarEmpleadoMouseClicked

    private void btnActualizarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarEmpleadoMouseClicked
        ActualizarEmpleado ventana = new ActualizarEmpleado (this,true,sistema);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnActualizarEmpleadoMouseClicked

    private void btnEliminarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoMouseClicked
        String idStr = JOptionPane.showInputDialog(this, 
        "Ingrese el ID del empleado a eliminar:", 
        "Eliminar Empleado", 
        JOptionPane.QUESTION_MESSAGE);
    
    if (idStr == null || idStr.isEmpty()) {
        return; // Usuario canceló
    }
    
    try {
        int id = Integer.parseInt(idStr);
        
        Empleado empleado = sistema.buscarEmpleado(id);
        
        if (empleado == null) {
            JOptionPane.showMessageDialog(this, 
                "No se encontró ningún empleado con ese ID", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro que desea eliminar al empleado:\n" + 
            empleado.getNombre() + " " + empleado.getApellido() + "?", 
            "Confirmar eliminación", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            Empleado eliminado = sistema.removerEmpleado(id);
            
            if (eliminado != null) {
                JOptionPane.showMessageDialog(this, 
                    "Empleado eliminado exitosamente", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Error al eliminar empleado", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "El ID debe ser un número", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEliminarEmpleadoMouseClicked

    private void btnGenerarReportEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReportEmpMouseClicked
        GenerarReportEmple ventana = new GenerarReportEmple(this,true,sistema);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnGenerarReportEmpMouseClicked

    private void btnGenerarReportDepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarReportDepMouseClicked
        GenerarReportDep ventana = new GenerarReportDep(this,true,sistema);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnGenerarReportDepMouseClicked
    
    private void configurarMenuSegunRol() {
    String rol = sistema.getRol();
    
    if (rol == null) return; // Protección por si el rol es null
    
    switch(rol) {
        case "ADMIN" -> {
            break;
            }// Admin ve todos los botones (no ocultar nada)
            
        case "JEFE_DEPARTAMENTO" -> {
            // Ocultar botones que no puede usar
            btnAsignarEmpleado.setVisible(false);
            btnActualizarEmpleado.setVisible(false);
            btnBuscarEmpleado.setVisible(false);
            btnEliminarEmpleado.setVisible(false);
            break; // Solo puede: Mostrar empleados, Reportes
            }
            
        case "EMPLEADO" -> {
            // Solo puede ver: Mostrar empleados y su reporte
            btnAsignarEmpleado.setVisible(false);
            btnEliminarEmpleado.setVisible(false);
            btnActualizarEmpleado.setVisible(false);
            btnBuscarEmpleado.setVisible(false);
            btnGenerarReportDep.setVisible(false);
            break;
            }
        
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnActualizarEmpleado;
    private javax.swing.JPanel btnAsignarEmpleado;
    private javax.swing.JPanel btnBuscarEmpleado;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JPanel btnEliminarEmpleado;
    private javax.swing.JPanel btnGenerarReportDep;
    private javax.swing.JPanel btnGenerarReportEmp;
    private javax.swing.JPanel btnMostrarEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblIconActualizarEmpleado;
    private javax.swing.JLabel lblIconAgregarEmpleado;
    private javax.swing.JLabel lblIconBuscarEmpleado;
    private javax.swing.JLabel lblIconEliminarEmpleado;
    private javax.swing.JLabel lblIconGenerarReportDep;
    private javax.swing.JLabel lblIconGenerarReportEmp;
    private javax.swing.JLabel lblIconMostrarEmpleado;
    private javax.swing.JLabel lblNombreActualizar;
    private javax.swing.JLabel lblNombreAgregar;
    private javax.swing.JLabel lblNombreBuscar;
    private javax.swing.JLabel lblNombreEliminar;
    private javax.swing.JLabel lblNombreGenerarReportDep;
    private javax.swing.JLabel lblNombreGenerarReportEmp;
    private javax.swing.JLabel lblNombreMostrar;
    // End of variables declaration//GEN-END:variables
}
